# Generated by Django 4.2.11 on 2024-04-14 03:35

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_campaign_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='funds_destination',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Destino de los fondos recaudados'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='beneficiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='campaigns.beneficiary', verbose_name='Beneficiario'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='campaigns.category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), db_index=True, help_text='Etiquetas de la publicación, ejemplo: tag1,tag2', size=32, verbose_name='Etiquetas de la campaña separadas por coma'),
        ),
    ]
