# Generated by Django 4.2.11 on 2024-04-14 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_beneficiary_funds_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='alternative_title',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Destino de los fondos recaudados'),
        ),
    ]
