# Generated by Django 4.2.11 on 2024-04-15 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethodBasedInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('bank', models.CharField(max_length=32, verbose_name='Banco')),
                ('code', models.CharField(db_index=True, max_length=17, verbose_name='Codigo del metodo')),
                ('icon', models.ImageField(upload_to='assets/', verbose_name='Imagen del metodo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('card_id', models.PositiveIntegerField()),
                ('payment_method', models.PositiveIntegerField(choices=[(0, 'Pagomovil'), (1, 'Transferencia Interbancaria'), (2, 'Transferecia bancaria'), (3, 'Divisas'), (4, 'Transferencia de divisas electronicas'), (5, 'Otras')])),
                ('account_named', models.CharField(max_length=85, verbose_name='Titular de la cuenta')),
                ('account_number', models.CharField(db_index=True, max_length=100, verbose_name='Número de cuenta')),
                ('based', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payment_methods', to='users.paymentmethodbasedinformation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
