# Generated by Django 4.2.11 on 2024-04-17 23:56

from django.db import migrations, models
import ingsoftware.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_paymentmethod_account_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, default='', help_text='Este dato se utilizara para control interno en esta aplicación.', max_length=250, verbose_name='Dirección de residencia'),
        ),
        migrations.AddField(
            model_name='user',
            name='alternative_phone',
            field=models.CharField(blank=True, default='', max_length=14, verbose_name='Número de teléfono alternativo'),
        ),
        migrations.AddField(
            model_name='user',
            name='card_id',
            field=models.PositiveIntegerField(db_index=True, default=None, null=True, verbose_name='Identificación'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=14, verbose_name='Número de teléfono'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default=None, null=True, upload_to=ingsoftware.users.models.user_directory_path, verbose_name='Foto de perfil'),
        ),
    ]
