# Generated by Django 4.2.11 on 2024-04-11 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaigns', '0002_alter_campaign_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total donado')),
                ('mark_as_annonymous', models.BooleanField(default=False, verbose_name='Marcar donativo como anonimo')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='donatives', to='campaigns.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('comment', models.CharField(max_length=250, verbose_name='Deja un comentario de apoyo')),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='donatives.donation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
