# Generated by Django 4.2.11 on 2024-04-11 23:26

from django.db import migrations, models
import ingsoftware.campaigns.models


class Migration(migrations.Migration):

    dependencies = [
        ('donatives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='payed_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='transaction_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=10, verbose_name='Codigo de la transaccion'),
        ),
        migrations.AddField(
            model_name='donation',
            name='voucher',
            field=models.FileField(default=None, null=True, upload_to=ingsoftware.campaigns.models.user_directory_path),
        ),
    ]
