version: '3'

services:
  docs:
    image: ingsoftware_local_docs
    container_name: ingsoftware_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./ingsoftware:/app/ingsoftware:z
    ports:
      - '9000:9000'
    command: /start-docs
